meta:
  releases:
  - name:    cf-rabbitmq
    version: 298.0.0
    url:     https://bosh.io/d/github.com/pivotal-cf/cf-rabbitmq-release?v=298.0.0
    sha1:    af49f66f70cd5d6ca50e21e9e3c755aaa965ae84

  - name:    cf-rabbitmq-multitenant-broker
    version: 72.0.0
    url:     https://bosh.io/d/github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release?v=72.0.0
    sha1:    3c5e72dd473a741e1a69a7d87042e4ad953ee50f

  - name:    cf-rabbitmq-smoke-tests
    version: 52.0.0
    url:     https://bosh.io/d/github.com/pivotal-cf/cf-rabbitmq-smoke-tests-release?v=52.0.0
    sha1:    30f4bb59aac84dfab70e846a08e1389ded561a34

  - name:    bpm
    version: 1.1.8 
    url:     https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.8
    sha1:    c956394fce7e74f741e4ae8c256b480904ad5942

  - name:    cf-cli
    version: 1.26.0
    url:     https://bosh.io/d/github.com/bosh-packages/cf-cli-release?v=1.26.0
    sha1:    ed3aef6b2b25cb7cec1b0eaff3b7c736374a2f47

  - name:    haproxy
    version: 10.1.0
    url:     https://bosh.io/d/github.com/cloudfoundry-incubator/haproxy-boshrelease?v=10.1.0
    sha1:    97fbb573fc04d36c548915d8daef12a547e722d6

  - name:    routing
    version: 0.201.0
    url:     https://bosh.io/d/github.com/cloudfoundry/routing-release?v=0.201.0
    sha1:    1048b130d823e62269ee692b244ad13067662a3c