#==================================================
# This file configures the RabbitMQ server cluster
#  and inbound traffic HAProxy
#==================================================

instance_groups:
- name: rmq-server
  instances: (( grab params.rmq_instances || 1 ))
  jobs:
  - name: rabbitmq-server
    release: cf-rabbitmq
    properties:
      rabbitmq-server:
        version: "3.8"
        plugins:
        - rabbitmq_management
        - rabbitmq_mqtt
        - rabbitmq_stomp
        ports:
        - 5672
        - 5671
        - 1883
        - 8883
        - 61613
        - 61614
        - 15671
        - 15672
        - 15674
        administrators:
          management:
            username: management
            password: (( vault meta.vault "/rabbitmq/admin/management:password" ))
          broker:
            username: broker
            password: (( vault meta.vault "/rabbitmq/admin/broker:password" ))
        cookie: (( vault meta.vault "/rabbitmq/erlang-cookie:cookie" ))
        cluster_partition_handling: pause_minority
        ssl:
          enabled: true
          key:    (( vault meta.vault "/rabbitmq/certs/server:key" ))
          cert:   (( vault meta.vault "/rabbitmq/certs/server:certificate" ))
          cacert: (( vault meta.vault "/rabbitmq/certs/ca:certificate" ))
          versions:
          - tlsv1.2
          # Verification is off because we don't currently have a way to
          # automagically sign the certificate for the IPs that the servers
          # will be dynamically assigned.
          verify:                    false
          verification_depth:        5
          fail_if_no_peer_cert:      true
        management_tls:
          enabled: true
          cacert:  (( vault meta.vault "/rabbitmq/certs/ca:certificate" ))
          cert:  (( vault meta.vault "/rabbitmq/certs/management:certificate" ))
          key:  (( vault meta.vault "/rabbitmq/certs/management:key" ))

  vm_type: (( grab params.server_vm_type || "rabbitmq" ))
  stemcell: default
  persistent_disk_type: (( grab params.server_disk_type || "rabbitmq" ))
  networks:
  - name: (( grab params.rabbitmq_network || "rabbitmq" ))
  azs: (( grab params.availability_zones || meta.default.azs ))

- name: haproxy
  instances: 1
  jobs:
  - name: rabbitmq-haproxy
    release: cf-rabbitmq
  - name: bpm
    release: bpm
  vm_type: (( grab params.proxy_vm_type || "small" ))
  stemcell: default
  networks:
  - name: (( grab params.rabbitmq_network || "rabbitmq" ))
    static_ips: (( static_ips 0 ))
  azs: (( grab params.availability_zones || meta.default.azs ))

releases:
- name: cf-rabbitmq
  .:    (( inject meta.releases.cf-rabbitmq ))
- name: bpm
  .:    (( inject meta.releases.bpm ))

exodus:
  management_url: (( concat "https://" instance_groups.haproxy.networks.0.static_ips.0 ":15672" ))
  management_username: (( grab instance_groups.rmq-server.jobs.rabbitmq-server.properties.rabbitmq-server.administrators.management.username ))
  management_password: (( grab instance_groups.rmq-server.jobs.rabbitmq-server.properties.rabbitmq-server.administrators.management.password ))