---
params:
  cf_deployment: (( concat meta.environment "-cf" ))
  registered_domain: (( concat meta.broker_route_subdomain "." meta.cf_system_domain ))

meta:
  broker:
    protocol: https
  broker_route_subdomain: rabbitmq-broker
  cf_system_domain: (( vault "secret/exodus/" meta.bosh_exodus_path "/cf:system_domain" ))

instance_groups:
- name: rmq-broker
  jobs:
  - name: route_registrar
    release: routing
    consumes:
      nats:
        from:       nats
        deployment: (( grab params.cf_deployment ))
      nats-tls: nil
    properties:
      route_registrar:
        routes:
        - name: (( concat params.broker_name "-broker" ))
          tls_port: 443
          registration_interval: 20s
          uris:
          - (( grab params.registered_domain ))
      host: (( grab params.broker_domain ))

  - name: broker-registrar
    properties:
      broker:
        host: (( concat params.registered_domain ":443" ))

exodus:
  broker_url: (( concat meta.broker.protocol "://" params.registered_domain ":443" ))

releases:
- name: routing
  .:    (( inject meta.releases.routing ))