---
- type: replace
  path: /instance_groups/name=rmq-server/jobs/name=bpm?
  value:
    name:    bpm
    release: bpm
- type: replace
  path: /instance_groups/name=rmq-server/jobs/name=route_registrar
  value: (( grab meta.mgmt_route_registrar_job ))
- type: remove
  path: /instance_groups/name=haproxy?