---
- type: remove
  path: /meta/mgmt_domain_route/routes/0/tls_port
- type: replace
  path: /meta/mgmt_domain_route/routes/0/port?
  value: 15672
- type: replace
  path: /instance_groups/name=rmq-broker/jobs/name=rabbitmq-service-broker/properties/dns_host?
  value: (( grab params.mgmt_domain ))